spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      routes:
        # IAM Service Routes
        - id: iam-service
          uri: http://iam-service:8081
          predicates:
            - Path=/api/v1/authentication/**,/api/v1/users/**,/api/v1/roles/**
        
        # IAM Service Swagger UI
        - id: iam-swagger-ui
          uri: http://iam-service:8081
          predicates:
            - Path=/iam/swagger-ui.html
          filters:
            - RewritePath=/iam/swagger-ui.html, /swagger-ui.html
        
        - id: iam-swagger-resources
          uri: http://iam-service:8081
          predicates:
            - Path=/iam/swagger-ui/**
          filters:
            - RewritePath=/iam/(?<segment>.*), /$${segment}
        
        - id: iam-api-docs
          uri: http://iam-service:8081
          predicates:
            - Path=/iam/v3/api-docs
          filters:
            - RewritePath=/iam/v3/api-docs, /api-docs
        - id: iam-api-docs-sub
          uri: http://iam-service:8081
          predicates:
            - Path=/iam/v3/api-docs/**
          filters:
            - RewritePath=/iam/v3/api-docs/(?<segment>.*), /api-docs/$${segment}
        
        # Profiles Service Routes
        - id: profiles-service
          uri: http://profiles-service:8082
          predicates:
            - Path=/api/v1/lawyers/**,/api/v1/clients/**,/api/v1/lawyer-specialties/**
        
        # Profiles Service Swagger UI
        - id: profiles-swagger-ui
          uri: http://profiles-service:8082
          predicates:
            - Path=/profiles/swagger-ui.html
          filters:
            - RewritePath=/profiles/swagger-ui.html, /swagger-ui.html
        
        - id: profiles-swagger-resources
          uri: http://profiles-service:8082
          predicates:
            - Path=/profiles/swagger-ui/**
          filters:
            - RewritePath=/profiles/(?<segment>.*), /$${segment}
        
        - id: profiles-api-docs
          uri: http://profiles-service:8082
          predicates:
            - Path=/profiles/v3/api-docs
          filters:
            - RewritePath=/profiles/v3/api-docs, /api-docs
        - id: profiles-api-docs-sub
          uri: http://profiles-service:8082
          predicates:
            - Path=/profiles/v3/api-docs/**
          filters:
            - RewritePath=/profiles/v3/api-docs/(?<segment>.*), /api-docs/$${segment}
        
        # Cases Service Routes
        - id: cases-service
          uri: http://cases-service:8083
          predicates:
            - Path=/api/v1/cases/**,/api/v1/applications/**,/api/v1/invitations/**,/api/v1/comments/**
        
        # Cases Service Swagger UI
        - id: cases-swagger-ui
          uri: http://cases-service:8083
          predicates:
            - Path=/cases/swagger-ui.html
          filters:
            - RewritePath=/cases/swagger-ui.html, /swagger-ui.html
        
        - id: cases-swagger-resources
          uri: http://cases-service:8083
          predicates:
            - Path=/cases/swagger-ui/**
          filters:
            - RewritePath=/cases/(?<segment>.*), /$${segment}
        
        - id: cases-api-docs
          uri: http://cases-service:8083
          predicates:
            - Path=/cases/v3/api-docs
          filters:
            - RewritePath=/cases/v3/api-docs, /api-docs
        - id: cases-api-docs-sub
          uri: http://cases-service:8083
          predicates:
            - Path=/cases/v3/api-docs/**
          filters:
            - RewritePath=/cases/v3/api-docs/(?<segment>.*), /api-docs/$${segment}

server:
  port: 8080

# Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: IAM Service
        url: /iam/v3/api-docs
      - name: Profiles Service
        url: /profiles/v3/api-docs
      - name: Cases Service
        url: /cases/v3/api-docs
    urls-primary-name: IAM Service

